sudo: required

arch:
  packages:
    - namcap 
  script:
    - namcap PKGBUILD      
    - makepkg --nodeps
    - namcap java-8-openjdk-shenandoah-*
    - pacman -Qip java-8-openjdk-shenandoah-*
    - pacman -Qlp java-8-openjdk-shenandoah-*
  

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
