[[server]]
address = "irc.rizon.net"
nickname = "parabot"
# optional: alternative_nicknames = ["weebot"]
nickserv_password = "test123"
# optional: server_password = "test123"
database = ".local/share/parabot/parabot.db" # Different servers may populate the same db
owners = ["nick1", "nick2"] # a list of nicks that may exec priviledged cmds
# optional: weather_api_secret = "secret" a https://darksky.net API secret
# optional: geocoding_api_key = "key" a https://developer.mapquest.com API key
# optional: wolframalpha_appid = "appid" a https://www.wolframalpha.com/ appid
# p√ºtional: youtube_api_key = "key" a https://console.developers.google.com api key
# optional: google_search_id = "id" a http://cse.google.com/all id
# optional: google_search_key = "key" a https://developers.google.com/custom-search/json-api/v1/introduction key
# optional: max_burst_messages = 4
# optional: burst_window_length = 8 # Time between bursts in seconds
# optional: wormy_nick = "nick" # nick of a wormy hivemind bot
port = 6697
	[[server.channel]]
	name = "#c"
	# optional: password = "channel_key"
	# optional: url_blacklisted_domains = ["google.com"]
	modules = ["duckduckgo", "google", "jisho", "url-info", "tell", "wolframalpha", "weather",
			   "wormy", "youtube", "choose"]
	[[server.channel]]
	name = "#news"
	modules = ["url-info", "weather"]
