# docs:
# https://github.com/be5invis/Iosevka

# ss## stylistic sets:
# https://raw.githubusercontent.com/be5invis/Iosevka/master/images/stylesets.png

# cv## character variants:
# https://raw.githubusercontent.com/be5invis/Iosevka/master/images/charvars.png

# ligset-* ligature sets:
# https://raw.githubusercontent.com/be5invis/Iosevka/master/images/ligations.png

[buildPlans.iosevka-custom]           # Plan name
family = "Iosevka Custom"             # Font menu family name
design = [                            # Common styles

  "cv05",                             # hooky i
  "cv14",                             # dotted 0
  "cv24",                             # open double story g
  "cv26",                             # short leg m
  "cv27",                             # tailed l
  "cv33",                             # short @
  "cv46",                             # flat top 3
  "cv53",                             # tailed f
  "cv54",                             # open short $
  "cv60",                             # hex *
  "cv69",                             # curly kK
  "cv72",                             # curly vV
  "cv74",                             # curly A
  "cv76",                             # curly wW
  "cv78",                             # curly xX
  "cv79",                             # curly y
  "cv81",                             # curly Y
  "cv83",                             # curly R

]
# upright = []                        # Upright-only styles
# italic = []                         # Italic-only styles
# oblique = []                        # Oblique-only styles

[buildPlans.iosevka-slab-custom]      # Plan name
family = "Iosevka Slab Custom"        # Font menu family name
design = [                            # Common styles

  "slab",

  "cv05",                             # hooky i
  "cv14",                             # dotted 0
  "cv24",                             # open double story g
  "cv26",                             # short leg m
  "cv27",                             # tailed l
  "cv33",                             # short @
  "cv46",                             # flat top 3
  "cv53",                             # tailed f
  "cv54",                             # open short $
  "cv60",                             # hex *
  "cv69",                             # curly kK
  "cv72",                             # curly vV
  "cv74",                             # curly A
  "cv76",                             # curly wW
  "cv78",                             # curly xX
  "cv79",                             # curly y
  "cv81",                             # curly Y
  "cv83",                             # curly R

]
# upright = []                        # Upright-only styles
# italic = []                         # Italic-only styles
# oblique = []                        # Oblique-only styles

[buildPlans.iosevka-term-custom]      # Plan name
family = "Iosevka Term Custom"        # Font menu family name
design = [                            # Common styles

  "term",                             # strict mono; no ligatures

  "cv05",                             # hooky i
  "cv14",                             # dotted 0
  "cv24",                             # open double story g
  "cv26",                             # short leg m
  "cv27",                             # tailed l
  "cv33",                             # short @
  "cv46",                             # flat top 3
  "cv53",                             # tailed f
  "cv54",                             # open short $
  "cv60",                             # hex *
  "cv69",                             # curly kK
  "cv72",                             # curly vV
  "cv74",                             # curly A
  "cv76",                             # curly wW
  "cv78",                             # curly xX
  "cv79",                             # curly y
  "cv81",                             # curly Y
  "cv83",                             # curly R

]
# upright = []                        # Upright-only styles
# italic = []                         # Italic-only styles
# oblique = []                        # Oblique-only styles

[buildPlans.iosevka-termlig-custom]   # Plan name
family = "Iosevka TermLig Custom"     # Font menu family name
design = [                            # Common styles

  "termlig",                          # strict mono; with ligatures

  "cv05",                             # hooky i
  "cv14",                             # dotted 0
  "cv24",                             # open double story g
  "cv26",                             # short leg m
  "cv27",                             # tailed l
  "cv33",                             # short @
  "cv46",                             # flat top 3
  "cv53",                             # tailed f
  "cv54",                             # open short $
  "cv60",                             # hex *
  "cv69",                             # curly kK
  "cv72",                             # curly vV
  "cv74",                             # curly A
  "cv76",                             # curly wW
  "cv78",                             # curly xX
  "cv79",                             # curly y
  "cv81",                             # curly Y
  "cv83",                             # curly R

]
# upright = []                        # Upright-only styles
# italic = []                         # Italic-only styles
# oblique = []                        # Oblique-only styles

[buildPlans.iosevka-term-slab-custom] # Plan name
family = "Iosevka Term Slab Custom"   # Font menu family name
design = [                            # Common styles

  "term",                             # strict mono; no ligatures
  "slab",

  "cv05",                             # hooky i
  "cv14",                             # dotted 0
  "cv24",                             # open double story g
  "cv26",                             # short leg m
  "cv27",                             # tailed l
  "cv33",                             # short @
  "cv46",                             # flat top 3
  "cv53",                             # tailed f
  "cv54",                             # open short $
  "cv60",                             # hex *
  "cv69",                             # curly kK
  "cv72",                             # curly vV
  "cv74",                             # curly A
  "cv76",                             # curly wW
  "cv78",                             # curly xX
  "cv79",                             # curly y
  "cv81",                             # curly Y
  "cv83",                             # curly R

]
# upright = []                        # Upright-only styles
# italic = []                         # Italic-only styles
# oblique = []                        # Oblique-only styles
