[version]
current = "2.5.3-1"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  -
  (?P<pkgrel>\d+)
'''

[git]
tag_template = "v{new_version}"
message_template = "Bump to {new_version}"

[[file]]
src = "PKGBUILD"
search = "pkgver={current_version}"
version_template="{major}.{minor}.{patch}"

[[file]]
src = "PKGBUILD"
search = "pkgrel={current_version}"
version_template="{pkgrel}"

[[before_commit]]
name = "Update source check sums"
cmd = "updpkgsums"

[[before_commit]]
name = "Check build"
cmd = "extra-x86_64-build"

[[before_commit]]
name = "Generate .SRCINFO"
cmd = "makepkg --printsrcinfo > .SRCINFO"
